theme: jekyll-theme-cayman
title: Welcome to Willi Blanco's Page
description: Welcome to my page! Here I am going to be updating and posting all of my projects! Feel free to bookmark this page and keep up with all my projects
